# Generated by Django 6.0.4 on 2026-04-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('nationalite', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('annee', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('couverture', models.ImageField(blank=True, upload_to='couvertures/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.auteur')),
            ],
        ),
    ]
